name: Docker Image CI

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set variables
      id: vars
      run: |
        export GIT_TAG=${GITHUB_REF#refs/*/}
        echo ::set-output name=python_version::${GIT_TAG%%-*}
        echo ::set-output name=build_version::${GIT_TAG##*-}
        echo ::set-output name=tag::$GIT_TAG
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          PYTHON_VERSION=${{ steps.vars.outputs.python_version }}
          BUILD_VERSION=${{ steps.vars.outputs.build_version }}
        tags: jyamad/python-build:${{ steps.vars.outputs.tag }}
